// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"atm-api.com/api/controllers"
	"atm-api.com/api/routes"
	"atm-api.com/repositories/withdrawal"
	"atm-api.com/services"
)

// Injectors from wire.go:

func InitializeWithdrawalRoutes() routes.WithdrawalRoutes {
	baseRepository := withdrawal.CreateDefaultRepository()
	banknoteDataService := services.CreateBanknoteService(baseRepository)
	withdrawalController := controllers.CreateWithdrawalController(banknoteDataService)
	withdrawalRoutes := routes.CreateWithdrawalRoutes(withdrawalController)
	return withdrawalRoutes
}
